### ISSUE TITLE
[Bug] Authentication done only by email

### ISSUE THREAD

**Issue by EAGLEARCHER** [Souvikparua/COMPLETE-Fullstack-ecommerce-Responsive-MERN-App#23]
**Issue Title:** Improve Authentication System for Signup and Login

**Description:**
The current setup for user authentication, specifically for signup and login, needs improvement to enhance security, user experience, and overall system integrity. Currently, the signup process relies on a minimal set of fields (firstName, lastName, email, password, confirmPassword, and image) with no generation of tokens. Additionally, the login process is solely based on email without adequate consideration for password security.

**Comment by EAGLEARCHER** [comment]
Hey @Souvikparua can you assign me this under SWOC'24

**Comment by Souvikparua** [comment]
Done

**Comment by EAGLEARCHER** [comment]
Can I also refractor the models with existing fields in order to implement the tokenization?

**Comment by Souvikparua** [comment]
Yes you can

**Comment by Souvikparua** [comment]
Done
